### ISSUE TITLE
Files get create, but aren't getting update when i am run the generate Dag file 

### ISSUE THREAD

**Issue by babaralishah** [astronomer/dynamic-dags-tutorial#3]
this is the image of the code of the generated file :
![image](https://user-images.githubusercontent.com/37935603/152154689-42d46e83-4757-4fcb-93fa-a51f0a9c4c1c.png)

below is the file that has been created:
![image](https://user-images.githubusercontent.com/37935603/152154765-413720b9-c08d-4804-9369-7b2f154962af.png)

**Comment by RezaRahmati** [comment]
Same issue here, you need to change this code 

```
    for line in fileinput.input(new_filename, inplace=True):
        line.replace("dag_id", "'"+config['DagId']+"'")
        line.replace("scheduletoreplace", config['Schedule'])
        line.replace("querytoreplace", config['Query'])
        print(line, end="")
```

to 
```
    for line in fileinput.input(new_filename, inplace=True):
        line = line.replace("dag_id", "'"+config['DagId']+"'")
        line = line.replace("scheduletoreplace", config['Schedule'])
        line = line.replace("querytoreplace", config['Query'])
        print(line, end="")
```

**Comment by babaralishah** [comment]
> Same issue here, you need to change this code
> 
> ```
>     for line in fileinput.input(new_filename, inplace=True):
>         line.replace("dag_id", "'"+config['DagId']+"'")
>         line.replace("scheduletoreplace", config['Schedule'])
>         line.replace("querytoreplace", config['Query'])
>         print(line, end="")
> ```
> 
> to
> 
> ```
>     for line in fileinput.input(new_filename, inplace=True):
>         line = line.replace("dag_id", "'"+config['DagId']+"'")
>         line = line.replace("scheduletoreplace", config['Schedule'])
>         line = line.replace("querytoreplace", config['Query'])
>         print(line, end="")
> ```

@RezaRahmati 
okay fine.
so should we use `inplace=True` in the loop expression or not,
I am thinking we should not use the inplace=True as we are assigning the line with the assignment operator.

**Comment by RezaRahmati** [comment]
It works when I use the above, feel free to check with True or False see if it's working
